# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  port:
    type: string
    default: "8080"
    description: GRPC port

  mlmd_grpc_server_image:
    type: string
    description: Docker image for MLMD gRPC server
